namespace LDrawPartLib
{
    internal enum PartStatus
    {
        None,
        MouseOver,
        Selected,
        Tracking
    }

    public enum Winding
    {
        CCW, // Default; Counter Clock Wise
        CW   // Clock Wise
    }

    public enum MetaCommandType
    {
        Comment = 0,
        BFC = 1,
        Author,
        Keywords
    }

    public enum PartTextures
    {
        Chrome,
        Pearlescent,
        Rubber,
        MatteMetallic,
        Metal
    }

    public enum PartColors
    {
        Current = 16,
        Edge = 24,
        Black = 0,
        Blue = 1,
        Green = 2,
        DarkTuquoise = 3,
        Red = 4,
        DarkPink = 5,
        Brown = 6,
        LightGray = 7,
        DarkGray = 8,
        LightBlue = 9,
        BrightGreen = 10,
        LightTurquoise = 11,
        Salmon = 12,
        Pink = 13,
        Yellow = 14,
        White = 15,
        BlueViolet = 23,
        Rust = 67,
        Tan = 19,
        Flesh = 92,
        Purple = 22,
        Violet = 68,
        SkyBlue = 82,
        Orange = 25,
        Magenta = 26,
        Lime = 27,
        ReddishBrown = 70,
        EarthOrange = 366,
        MaerskBlue = 313,
        FabulandBrown = 31,
        TransparentBlack = 32,
        TransparentDarkBlue = 33,
        TransparentGreen = 34,
        TransparentRed = 36,
        TransparentPurple = 37,
        TransparentBrown = 38,
        TransparentLightGray = 39,
        TransparentDarkGray = 40,
        TransparentLightBlue = 41,
        TransparentNeonGreen = 42,
        TransparentMediumBlue = 43,
        TransparentDarkPink = 44,
        TransparentPink = 45,
        TransparentYellow = 46,
        TransparentWhite = 47,
        TransparentVeryLtBlue = 48,
        TransparentLightPurple = 49,
        TransparentBrightGreen = 50,
        TransparentOrange = 52,
        TransparentNeonYellow = 53,
        TransparentNeonOrange = 57,
        GlitterTransparentClear = 61,
        GlitterTransparentDarkPink = 62,
        GlitterTransparentPurple = 63,
        Aqua = 87,
        BrightLightBlue = 64,
        BrightLightOrange = 65,
        BrightLightYellow = 66,
        BrightPink = 88,
        LightFlesh = 78,
        LightGreen = 17,
        LightLime = 76,
        LightOrange4 = 62,
        LightBluishGray = 71,
        DarkBluishGray = 72,
        DarkBlue = 272,
        DarkBlueViolet = 89,
        DarkBrown = 75,
        DarkFlesh = 86,
        DarkGreen = 88,
        DarkPurple = 85,
        DarkTurquoise = 79,
        DarkOrange = 484,
        DarkRed = 320,
        DarkTan = 28,
        LightPink = 77,
        LightPurple = 29,
        LightSalmon = 81,
        LightViolet = 20,
        LightYellow = 18,
        MediumBlue = 73,
        MediumDarkPink = 90,
        MediumGreen = 74,
        MediumLime = 93,
        MediumOrange = 91,
        MediumViolet = 69,
        SandBlue = 379,
        SandGreen = 378,
        SandPurple = 373,
        SandRed = 335,
        VeryLightBluishGray = 151,
        VeryLightGray = 503,
        VeryLightOrange = 504,
        ChromeAntiqueBrass = 384,
        ChromeBlue = 380,
        ChromeGold = 334,
        ChromeGreen = 381,
        ChromePink = 382,
        ChromeSilver = 383,
        ElectricContact = 494,
        MetallicGold = 495,
        MetallicGreen496,
        MetallicSilver = 497,
        FlatDarkGold = 132,
        FlatSilver = 133,
        Copper = 134,
        PearlDarkGray = 135,
        PearlGold = 142,
        PearlLightGold = 136,
        PearlLightGray = 138,
        PearlVeryLightGray = 139,
        PearlWhite = 140,
        MetalBlue = 137,
        GlowInDarkOpaque = 21,
        GlowInDarkTransparent = 80,
        MilkyWhite = 179,
        RubberBlack = 256,
        RubberBlue = 273,
        RubberGray = 375,
        RubberRed = 324,
        RubberWhite = 511,
        SpeckleBlackCopper = 176,
        SpeckleBlackSilver = 177,
        SpeckleDbGraySilver = 178,
    }
}
